name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer html5validator
        run: |
          sudo apt-get install python3-pip -y
          pip3 install html5validator
      - name: Vérifier le HTML
        run: |
          html5validator --root .

      - name: Linter CSS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: |
          npm install stylelint stylelint-config-standard --save-dev
          echo '{ "extends": "stylelint-config-standard" }' > .stylelintrc.json
          npx stylelint "**/*.css"
